import { ContentSource, Interest, SmartfeedSourceRule, SourceCandidate, UserInterestPreference } from "../types/content";

export const contentSources: ContentSource[] = [
  {
    id: "atl-mag",
    name: "Atlanta Magazine",
    type: "rss",
    url: "https://www.atlantamagazine.com/feed/",
    officialFeedUrl: "https://www.atlantamagazine.com/feed/",
    websiteUrl: "https://www.atlantamagazine.com",
    allowedFeedIds: ["atlanta"],
    eligibleSmartfeedIds: ["atlanta", "food-culture", "creative-community"],
    purpose: ["food_travel", "local_official", "culture_books"],
    defaultTopics: ["atlanta", "culture", "food"],
    defaultItemType: "external_article",
    supportedLocations: ["Atlanta"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Official feed URL configured. Confirm commercial mobile redistribution terms before production activation.",
    includedKeywords: ["atlanta", "neighborhood", "food", "arts", "events", "weekend"],
    excludedKeywords: ["sponsored", "giveaway", "celebrity"],
    minimumCandidateScore: 50,
    maximumItemsPerEdition: 2,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: true
  },
  {
    id: "city-atlanta",
    name: "City of Atlanta",
    type: "public_notice",
    url: "https://www.atlantaga.gov/Home/Components/News/News/",
    officialFeedUrl: "https://www.atlantaga.gov/Home/Components/News/News/",
    websiteUrl: "https://www.atlantaga.gov",
    allowedFeedIds: ["atlanta"],
    eligibleSmartfeedIds: ["atlanta"],
    purpose: ["local_official"],
    defaultTopics: ["atlanta", "public-notice"],
    defaultItemType: "official_update",
    supportedLocations: ["Atlanta"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Public source for official city updates. Route only useful notices, closures, events, and civic updates into finite editions.",
    includedKeywords: ["closure", "transit", "street", "public", "permit", "notice"],
    excludedKeywords: ["bid opportunity", "procurement"],
    minimumCandidateScore: 45,
    maximumItemsPerEdition: 1,
    preferredPlacement: "today",
    trustLevel: "known",
    cadence: "daily",
    enabled: true
  },
  {
    id: "indie-design-radio",
    name: "Independent Design Radio",
    type: "podcast",
    url: "https://example.com/independent-design-radio.xml",
    officialFeedUrl: "https://example.com/independent-design-radio.xml",
    websiteUrl: "https://example.com/independent-design-radio",
    allowedFeedIds: ["creative-community"],
    eligibleSmartfeedIds: ["creative-community"],
    purpose: ["design_creativity"],
    defaultTopics: ["creative-community", "ux-design"],
    defaultItemType: "external_podcast",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "paused",
    verificationStatus: "needs_review",
    syndicationNotes: "Audio lane candidate only. Keep paused until an official podcast feed and reuse terms are verified.",
    includedKeywords: ["design", "attention", "studio", "creative", "portfolio", "publishing"],
    excludedKeywords: ["crypto", "webinar"],
    minimumCandidateScore: 48,
    maximumItemsPerEdition: 2,
    preferredPlacement: "discovery",
    trustLevel: "community",
    cadence: "weekly",
    enabled: false
  },
  {
    id: "black-enterprise",
    name: "Black Enterprise",
    type: "rss",
    url: "https://www.blackenterprise.com/feed/",
    officialFeedUrl: "https://www.blackenterprise.com/feed/",
    websiteUrl: "https://www.blackenterprise.com",
    allowedFeedIds: ["black-tech"],
    eligibleSmartfeedIds: ["black-tech"],
    purpose: ["business_careers", "african_diaspora"],
    defaultTopics: ["business", "career", "technology"],
    defaultItemType: "external_article",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "needs_review",
    syndicationNotes: "Feed URL configured. Keep strong filters for celebrity, promo, and thin wealth content before production activation.",
    includedKeywords: ["black", "founder", "entrepreneur", "business", "career", "startup", "technology"],
    excludedKeywords: ["celebrity gossip", "sponsored", "sweepstakes", "luxury"],
    minimumCandidateScore: 48,
    maximumItemsPerEdition: 2,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: true
  },
  {
    id: "hypepotamus",
    name: "Hypepotamus",
    type: "rss",
    url: "https://hypepotamus.com/feed/",
    officialFeedUrl: "https://hypepotamus.com/feed/",
    websiteUrl: "https://hypepotamus.com",
    allowedFeedIds: ["atlanta", "black-tech"],
    eligibleSmartfeedIds: ["atlanta", "black-tech"],
    purpose: ["business_careers", "science_technology"],
    defaultTopics: ["atlanta", "startups", "technology"],
    defaultItemType: "external_article",
    supportedLocations: ["Atlanta", "Southeast"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "needs_review",
    syndicationNotes: "Useful regional startup source. Limit volume and prioritize founder stories, ecosystem context, events, and practical opportunities.",
    includedKeywords: ["atlanta", "startup", "founder", "southeast", "georgia", "technology"],
    excludedKeywords: ["sponsored", "job board", "press release"],
    minimumCandidateScore: 52,
    maximumItemsPerEdition: 1,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: true
  },
  {
    id: "the-conversation",
    name: "The Conversation",
    type: "atom",
    url: "https://theconversation.com/us/articles.atom",
    officialFeedUrl: "https://theconversation.com/us/articles.atom",
    websiteUrl: "https://theconversation.com/us",
    allowedFeedIds: ["black-tech", "creative-community", "food-culture", "faith-community"],
    eligibleSmartfeedIds: ["black-tech", "creative-community", "food-culture", "faith-community"],
    purpose: ["expert_context", "science_technology", "culture_books"],
    defaultTopics: ["science", "technology", "culture", "education", "society"],
    defaultItemType: "external_article",
    supportedLocations: ["Global", "United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Use topical or regional feeds when possible. Strict filtering keeps broad expert context from becoming general news.",
    includedKeywords: ["science", "technology", "education", "society", "culture", "research"],
    excludedKeywords: ["election horse race", "celebrity", "polling"],
    minimumCandidateScore: 52,
    maximumItemsPerEdition: 1,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: true
  },
  {
    id: "smithsonian",
    name: "Smithsonian Magazine",
    type: "rss",
    sourceDirectoryUrl: "https://www.smithsonianmag.com/rss/",
    websiteUrl: "https://www.smithsonianmag.com",
    allowedFeedIds: ["creative-community", "food-culture"],
    eligibleSmartfeedIds: ["creative-community", "food-culture"],
    purpose: ["curiosity_evergreen", "science_technology", "culture_books", "food_travel"],
    defaultTopics: ["history", "science", "culture", "travel", "education"],
    defaultItemType: "external_article",
    supportedLocations: ["Global", "United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Official RSS directory verified. Choose category feeds such as Science, History, Innovation, Arts and Culture, or Travel before enabling exact ingestion.",
    includedKeywords: ["history", "science", "innovation", "culture", "travel", "nature"],
    excludedKeywords: ["sponsored", "photo contest"],
    minimumCandidateScore: 54,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "known",
    cadence: "daily",
    enabled: false,
    lastVerifiedAt: "2026-07-18T00:00:00.000Z"
  },
  {
    id: "mit-news",
    name: "MIT News",
    type: "rss",
    sourceDirectoryUrl: "https://news.mit.edu/rss",
    websiteUrl: "https://news.mit.edu",
    allowedFeedIds: ["black-tech", "creative-community"],
    eligibleSmartfeedIds: ["black-tech", "creative-community"],
    purpose: ["science_technology", "expert_context", "business_careers", "design_creativity"],
    defaultTopics: ["technology", "science", "education", "business", "ux-design"],
    defaultItemType: "external_article",
    supportedLocations: ["Global", "United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Official RSS directory verified. Prefer school or topic feeds over the broad latest feed.",
    includedKeywords: ["technology", "science", "engineering", "architecture", "business", "education"],
    excludedKeywords: ["campus award", "obituary"],
    minimumCandidateScore: 54,
    maximumItemsPerEdition: 1,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: false,
    lastVerifiedAt: "2026-07-18T00:00:00.000Z"
  },
  {
    id: "nasa",
    name: "NASA",
    type: "rss",
    sourceDirectoryUrl: "https://www.nasa.gov/rss-feeds/",
    websiteUrl: "https://www.nasa.gov",
    allowedFeedIds: ["creative-community"],
    eligibleSmartfeedIds: ["creative-community"],
    purpose: ["science_technology", "curiosity_evergreen", "expert_context"],
    defaultTopics: ["science", "technology", "space", "education", "climate"],
    defaultItemType: "external_article",
    supportedLocations: ["Global", "United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Official NASA RSS directory verified. Use general-interest or mission feeds with strict topic matching.",
    includedKeywords: ["space", "science", "earth", "technology", "climate", "education"],
    excludedKeywords: ["media advisory", "contract award"],
    minimumCandidateScore: 54,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "known",
    cadence: "daily",
    enabled: false,
    lastVerifiedAt: "2026-07-18T00:00:00.000Z"
  },
  {
    id: "atlanta-fed",
    name: "Atlanta Federal Reserve",
    type: "rss",
    sourceDirectoryUrl: "https://www.atlantafed.org/rss",
    websiteUrl: "https://www.atlantafed.org",
    allowedFeedIds: ["atlanta", "black-tech"],
    eligibleSmartfeedIds: ["atlanta", "black-tech"],
    purpose: ["business_careers", "expert_context", "local_official"],
    defaultTopics: ["business", "work", "economics", "education", "atlanta"],
    defaultItemType: "external_article",
    supportedLocations: ["Atlanta", "Southeast", "United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "Official RSS directory verified and notes free use subject to legal notices. Prefer publications, employment, small business, and regional economy material over press release volume.",
    includedKeywords: ["economy", "employment", "small business", "regional", "workforce", "financial education"],
    excludedKeywords: ["press release", "appointment", "minutes"],
    minimumCandidateScore: 52,
    maximumItemsPerEdition: 1,
    preferredPlacement: "both",
    trustLevel: "known",
    cadence: "daily",
    enabled: false,
    lastVerifiedAt: "2026-07-18T00:00:00.000Z"
  },
  {
    id: "national-park-service",
    name: "National Park Service",
    type: "rss",
    sourceDirectoryUrl: "https://www.nps.gov/feeds/rss-help.htm",
    websiteUrl: "https://www.nps.gov",
    allowedFeedIds: ["creative-community", "food-culture"],
    eligibleSmartfeedIds: ["creative-community", "food-culture"],
    purpose: ["food_travel", "curiosity_evergreen", "local_official"],
    defaultTopics: ["travel", "history", "nature", "events", "public-notice"],
    defaultItemType: "official_update",
    supportedLocations: ["United States"],
    supportedLanguages: ["en"],
    status: "active",
    verificationStatus: "verified",
    syndicationNotes: "NPS RSS help page verified. Enable only park-specific or topic-specific feeds relevant to a user's interests or saved places.",
    includedKeywords: ["park", "history", "event", "trail", "nature", "travel"],
    excludedKeywords: ["fee collection", "contract", "administrative"],
    minimumCandidateScore: 54,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "known",
    cadence: "daily",
    enabled: false,
    lastVerifiedAt: "2026-07-18T00:00:00.000Z"
  },
  {
    id: "mental-floss",
    name: "Mental Floss",
    type: "rss",
    url: "https://www.mentalfloss.com/rss.xml",
    officialFeedUrl: "https://www.mentalfloss.com/rss.xml",
    websiteUrl: "https://www.mentalfloss.com",
    allowedFeedIds: ["creative-community", "food-culture", "travel"],
    eligibleSmartfeedIds: ["creative-community", "food-culture", "travel"],
    purpose: ["curiosity_evergreen", "culture_books"],
    defaultTopics: ["science", "history", "culture", "food", "travel"],
    defaultItemType: "external_article",
    supportedLocations: ["Global", "United States"],
    supportedLanguages: ["en"],
    status: "paused",
    verificationStatus: "needs_review",
    syndicationNotes: "Useful lightweight discovery source, but keep paused until feed health and commercial reuse terms are verified.",
    includedKeywords: ["history", "language", "books", "science", "culture", "geography"],
    excludedKeywords: ["shopping", "deals", "celebrity", "quiz"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "jstor-daily",
    name: "JSTOR Daily",
    type: "rss",
    websiteUrl: "https://daily.jstor.org",
    allowedFeedIds: ["creative-community", "faith-community"],
    eligibleSmartfeedIds: ["creative-community", "faith-community"],
    purpose: ["expert_context", "curiosity_evergreen", "culture_books"],
    defaultTopics: ["history", "society", "culture", "education", "research"],
    defaultItemType: "external_article",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Strong conceptual fit, but official feed and reuse terms need verification before enabling.",
    includedKeywords: ["history", "research", "society", "books", "culture", "education"],
    excludedKeywords: ["sponsored"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    type: "public_api",
    websiteUrl: "https://news.ycombinator.com",
    allowedFeedIds: ["black-tech"],
    eligibleSmartfeedIds: ["black-tech"],
    purpose: ["science_technology", "business_careers"],
    defaultTopics: ["technology", "business", "work", "startups"],
    defaultItemType: "link",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Use official public API only. Prefer external-link items and do not import points as ranking signals.",
    includedKeywords: ["software", "startup", "product", "developer", "open source", "security"],
    excludedKeywords: ["show hn", "ask hn", "launch", "funding"],
    minimumCandidateScore: 58,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "hourly",
    enabled: false
  },
  {
    id: "techcabal",
    name: "TechCabal",
    type: "rss",
    websiteUrl: "https://techcabal.com",
    allowedFeedIds: ["black-tech"],
    eligibleSmartfeedIds: ["black-tech"],
    purpose: ["african_diaspora", "science_technology", "business_careers"],
    defaultTopics: ["technology", "business", "startups", "africa"],
    defaultItemType: "external_article",
    supportedLocations: ["Africa", "Nigeria", "Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Potential African technology source. Verify official feed and reuse terms before enabling.",
    includedKeywords: ["africa", "startup", "technology", "digital economy", "founder", "career"],
    excludedKeywords: ["funding announcement", "sponsored"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "both",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "african-arguments",
    name: "African Arguments",
    type: "rss",
    websiteUrl: "https://africanarguments.org",
    allowedFeedIds: ["faith-community", "creative-community"],
    eligibleSmartfeedIds: ["faith-community", "creative-community"],
    purpose: ["african_diaspora", "expert_context"],
    defaultTopics: ["society", "policy", "africa", "culture"],
    defaultItemType: "external_article",
    supportedLocations: ["Africa", "Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Best for contextual reading. Verify official feed and avoid letting political breaking news dominate.",
    includedKeywords: ["africa", "society", "policy", "community", "culture"],
    excludedKeywords: ["horse race", "party politics"],
    minimumCandidateScore: 58,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "okayafrica",
    name: "OkayAfrica",
    type: "rss",
    websiteUrl: "https://www.okayafrica.com",
    allowedFeedIds: ["creative-community"],
    eligibleSmartfeedIds: ["creative-community"],
    purpose: ["african_diaspora", "culture_books"],
    defaultTopics: ["culture", "music", "arts", "film", "identity"],
    defaultItemType: "external_article",
    supportedLocations: ["Africa", "Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Potential culture source. Verify official feed and filter promotional entertainment content.",
    includedKeywords: ["africa", "diaspora", "culture", "music", "film", "arts"],
    excludedKeywords: ["sponsored", "red carpet", "celebrity"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "literary-hub",
    name: "Literary Hub",
    type: "rss",
    websiteUrl: "https://lithub.com",
    allowedFeedIds: ["creative-community"],
    eligibleSmartfeedIds: ["creative-community"],
    purpose: ["culture_books", "design_creativity"],
    defaultTopics: ["books", "publishing", "writing", "culture"],
    defaultItemType: "external_article",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Promising books and publishing source. Verify official feed and apply strict volume limits.",
    includedKeywords: ["books", "publishing", "writing", "essay", "interview"],
    excludedKeywords: ["book deal", "celebrity"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "atlas-obscura",
    name: "Atlas Obscura",
    type: "rss",
    websiteUrl: "https://www.atlasobscura.com",
    allowedFeedIds: ["creative-community", "food-culture"],
    eligibleSmartfeedIds: ["creative-community", "food-culture"],
    purpose: ["curiosity_evergreen", "food_travel", "culture_books"],
    defaultTopics: ["travel", "history", "culture", "places", "food"],
    defaultItemType: "external_article",
    supportedLocations: ["Global"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Good Discovery candidate. Verify official feed and keep travel feeds from becoming trivia-only.",
    includedKeywords: ["travel", "history", "place", "culture", "food"],
    excludedKeywords: ["sponsored", "deal"],
    minimumCandidateScore: 56,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  },
  {
    id: "npr-topical",
    name: "NPR Topical Feeds",
    type: "rss",
    websiteUrl: "https://www.npr.org",
    allowedFeedIds: ["creative-community", "food-culture"],
    eligibleSmartfeedIds: ["creative-community", "food-culture"],
    purpose: ["culture_books", "expert_context", "curiosity_evergreen"],
    defaultTopics: ["culture", "books", "food", "science", "identity"],
    defaultItemType: "external_article",
    supportedLocations: ["United States"],
    supportedLanguages: ["en"],
    status: "experimental",
    verificationStatus: "unverified",
    syndicationNotes: "Use selected official topical feeds only. Verify current feed directory and licensing before production activation.",
    includedKeywords: ["books", "culture", "food", "science", "climate", "identity"],
    excludedKeywords: ["breaking news", "election horse race"],
    minimumCandidateScore: 58,
    maximumItemsPerEdition: 1,
    preferredPlacement: "discovery",
    trustLevel: "experimental",
    cadence: "daily",
    enabled: false
  }
];

export const smartfeedSourceRules: SmartfeedSourceRule[] = [
  {
    id: "atl-mag-atlanta",
    sourceId: "atl-mag",
    feedId: "atlanta",
    enabled: true,
    status: "active",
    allowedTopicIds: ["atlanta", "culture", "food", "creative-community"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    requiredLocationIds: ["atlanta"],
    includedKeywords: ["atlanta", "neighborhood", "weekend", "gallery", "bookstore", "food"],
    excludedKeywords: ["sponsored", "celebrity", "giveaway"],
    minimumRelevanceScore: 50,
    sourcePriority: 8,
    maxItemsPerEdition: 2
  },
  {
    id: "city-atlanta-atlanta",
    sourceId: "city-atlanta",
    feedId: "atlanta",
    enabled: true,
    status: "active",
    allowedTopicIds: ["atlanta", "public-notice"],
    excludedTopicIds: [],
    allowedItemTypes: ["official_update"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    requiredLocationIds: ["atlanta"],
    includedKeywords: ["closure", "transit", "street", "public", "permit", "notice"],
    excludedKeywords: ["bid opportunity", "procurement"],
    minimumRelevanceScore: 45,
    sourcePriority: 9,
    maxItemsPerEdition: 1
  },
  {
    id: "indie-design-creative",
    sourceId: "indie-design-radio",
    feedId: "creative-community",
    enabled: true,
    status: "active",
    allowedTopicIds: ["ux-design", "creative-community", "culture", "work"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_podcast"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["design", "attention", "studio", "creative", "portfolio", "publishing"],
    excludedKeywords: ["crypto", "webinar"],
    minimumRelevanceScore: 48,
    sourcePriority: 7,
    maxItemsPerEdition: 2
  },
  {
    id: "black-enterprise-black-tech",
    sourceId: "black-enterprise",
    feedId: "black-tech",
    enabled: true,
    status: "active",
    allowedTopicIds: ["technology", "business", "work", "society"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["black", "founder", "entrepreneur", "business", "career", "startup", "technology"],
    excludedKeywords: ["celebrity gossip", "sponsored", "sweepstakes"],
    minimumRelevanceScore: 48,
    sourcePriority: 8,
    maxItemsPerEdition: 2
  },
  {
    id: "hypepotamus-atlanta",
    sourceId: "hypepotamus",
    feedId: "atlanta",
    enabled: true,
    status: "active",
    allowedTopicIds: ["atlanta", "technology", "business", "work"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    requiredLocationIds: ["atlanta"],
    includedKeywords: ["atlanta", "startup", "founder", "southeast", "georgia", "midtown"],
    excludedKeywords: ["sponsored", "job board", "press release"],
    minimumRelevanceScore: 52,
    sourcePriority: 8,
    maxItemsPerEdition: 1
  },
  {
    id: "hypepotamus-black-tech",
    sourceId: "hypepotamus",
    feedId: "black-tech",
    enabled: true,
    status: "active",
    allowedTopicIds: ["technology", "business", "work"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["founder", "startup", "technology", "ai", "operator", "funding"],
    excludedKeywords: ["sponsored", "job board", "press release"],
    minimumRelevanceScore: 52,
    sourcePriority: 7,
    maxItemsPerEdition: 1
  },
  {
    id: "the-conversation-black-tech",
    sourceId: "the-conversation",
    feedId: "black-tech",
    enabled: true,
    status: "experimental",
    allowedTopicIds: ["technology", "business", "work", "society", "science"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["technology", "ai", "labor", "equity", "startup", "work", "innovation"],
    excludedKeywords: ["election horse race", "celebrity", "polling"],
    minimumRelevanceScore: 54,
    sourcePriority: 7,
    maxItemsPerEdition: 1
  },
  {
    id: "the-conversation-creative",
    sourceId: "the-conversation",
    feedId: "creative-community",
    enabled: true,
    status: "experimental",
    allowedTopicIds: ["culture", "science", "society", "ux-design", "creative-community"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["culture", "design", "arts", "books", "media", "attention", "creative"],
    excludedKeywords: ["election horse race", "celebrity"],
    minimumRelevanceScore: 52,
    sourcePriority: 7,
    maxItemsPerEdition: 1
  },
  {
    id: "the-conversation-food",
    sourceId: "the-conversation",
    feedId: "food-culture",
    enabled: true,
    status: "experimental",
    allowedTopicIds: ["food", "health", "science", "culture", "society"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["food", "health", "nutrition", "culture", "restaurant", "climate"],
    excludedKeywords: ["diet fad", "celebrity"],
    minimumRelevanceScore: 52,
    sourcePriority: 6,
    maxItemsPerEdition: 1
  },
  {
    id: "the-conversation-faith",
    sourceId: "the-conversation",
    feedId: "faith-community",
    enabled: true,
    status: "experimental",
    allowedTopicIds: ["society", "culture", "faith"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["ethics", "religion", "community", "care", "meaning", "faith"],
    excludedKeywords: ["partisan attack", "celebrity"],
    minimumRelevanceScore: 52,
    sourcePriority: 6,
    maxItemsPerEdition: 1
  },
  {
    id: "mental-floss-creative",
    sourceId: "mental-floss",
    feedId: "creative-community",
    enabled: false,
    status: "paused",
    allowedTopicIds: ["culture", "science", "creative-community"],
    excludedTopicIds: [],
    allowedItemTypes: ["external_article"],
    excludedItemTypes: [],
    allowedLanguages: ["en"],
    includedKeywords: ["history", "language", "books", "science", "culture", "design"],
    excludedKeywords: ["shopping", "deals", "celebrity"],
    minimumRelevanceScore: 56,
    sourcePriority: 4,
    maxItemsPerEdition: 1
  }
];

export const interests: Interest[] = [
  { id: "atlanta", label: "Atlanta", keywords: ["atlanta", "decatur", "beltline", "grant park"], locationKeywords: ["atlanta"] },
  { id: "ux-design", label: "UX Design", keywords: ["ux", "design", "interface", "attention", "portfolio"] },
  { id: "technology", label: "Technology", keywords: ["technology", "tech", "ai", "software", "interface", "startup"] },
  { id: "business", label: "Business", keywords: ["business", "founder", "entrepreneur", "funding", "operator"] },
  { id: "work", label: "Work", keywords: ["work", "career", "labor", "workplace", "workers"] },
  { id: "food", label: "Local Food", keywords: ["food", "restaurant", "market", "coffee", "dining"] },
  { id: "public-notice", label: "Public Notice", keywords: ["closure", "transit", "notice", "permit", "street"] },
  { id: "creative-community", label: "Creative Community", keywords: ["creative", "studio", "publishing", "artist", "portfolio"] },
  { id: "science", label: "Science", keywords: ["science", "research", "study", "climate", "health"] },
  { id: "society", label: "Society", keywords: ["society", "community", "education", "ethics", "religion"] },
  { id: "culture", label: "Culture", keywords: ["culture", "arts", "books", "history", "language"] },
  { id: "education", label: "Education", keywords: ["education", "school", "learning", "research"] },
  { id: "health", label: "Health and Wellbeing", keywords: ["health", "wellbeing", "nutrition", "care"] },
  { id: "faith", label: "Faith and Spiritual Life", keywords: ["faith", "religion", "spiritual", "ethics", "meaning"] },
  { id: "travel", label: "Travel", keywords: ["travel", "place", "city", "destination", "guide"] },
  { id: "history", label: "History", keywords: ["history", "language", "archive", "past"] }
];

export const defaultUserInterestPreference: UserInterestPreference = {
  primaryInterestIds: ["atlanta", "technology", "ux-design"],
  secondaryInterestIds: ["business", "work", "food", "creative-community", "culture", "science", "society", "education"],
  location: "Atlanta",
  language: "en",
  preferredItemTypes: ["external_article", "external_podcast", "official_update"],
  mutedSourceIds: [],
  mutedInterestIds: [],
  openedCandidateUrls: []
};

export const sourceCandidateFixtures: SourceCandidate[] = [
  {
    id: "candidate-atl-culture-guide",
    sourceId: "atl-mag",
    sourceName: "Atlanta Magazine",
    feedId: "atlanta",
    state: "imported",
    suggestedItemType: "external_article",
    title: "A new weekend guide to small cultural spaces across Atlanta",
    excerpt: "A compact guide to galleries, listening rooms, bookstores, and neighborhood events worth keeping on your radar.",
    url: "https://www.atlantamagazine.com/culture/weekend-guide?utm_source=rss",
    canonicalUrl: "https://www.atlantamagazine.com/culture/weekend-guide",
    guid: "atl-mag-weekend-guide",
    publishedAt: "2026-07-17T09:00:00.000Z",
    fetchedAt: "2026-07-17T10:00:00.000Z",
    language: "en",
    categories: ["Atlanta", "Culture", "Weekend"]
  },
  {
    id: "candidate-atl-closure",
    sourceId: "city-atlanta",
    sourceName: "City of Atlanta",
    feedId: "atlanta",
    state: "imported",
    suggestedItemType: "official_update",
    title: "Weekend street closure notice for downtown events",
    excerpt: "Closures, transit notes, and expected reopening times for downtown events.",
    url: "https://www.atlantaga.gov/news/street-closure-downtown",
    canonicalUrl: "https://www.atlantaga.gov/news/street-closure-downtown",
    guid: "city-atlanta-street-closure",
    publishedAt: "2026-07-17T06:30:00.000Z",
    fetchedAt: "2026-07-17T10:00:00.000Z",
    language: "en",
    categories: ["Public Notice", "Transit"]
  },
  {
    id: "candidate-design-attention",
    sourceId: "indie-design-radio",
    sourceName: "Independent Design Radio",
    feedId: "creative-community",
    state: "imported",
    suggestedItemType: "external_podcast",
    title: "Designing for slower attention",
    excerpt: "A conversation about editorial interfaces, smaller social spaces, and the value of letting people read before reacting.",
    url: "https://example.com/episodes/designing-for-slower-attention",
    canonicalUrl: "https://example.com/episodes/designing-for-slower-attention",
    guid: "indie-design-slower-attention",
    publishedAt: "2026-07-16T15:00:00.000Z",
    fetchedAt: "2026-07-17T10:00:00.000Z",
    language: "en",
    categories: ["Design", "Attention"]
  },
  {
    id: "candidate-black-enterprise-founder-career",
    sourceId: "black-enterprise",
    sourceName: "Black Enterprise",
    feedId: "black-tech",
    state: "imported",
    suggestedItemType: "external_article",
    title: "A practical career signal for Black founders building through uncertainty",
    excerpt: "A business and career piece with useful context for founders, operators, and builders looking for grounded next steps.",
    url: "https://www.blackenterprise.com/black-founders-career-signal?utm_source=rss",
    canonicalUrl: "https://www.blackenterprise.com/black-founders-career-signal",
    guid: "black-enterprise-founder-career-signal",
    publishedAt: "2026-07-17T12:15:00.000Z",
    fetchedAt: "2026-07-17T13:00:00.000Z",
    language: "en",
    categories: ["Business", "Career", "Technology"]
  },
  {
    id: "candidate-hypepotamus-atlanta-link-sharing",
    sourceId: "hypepotamus",
    sourceName: "Hypepotamus",
    feedId: "atlanta",
    state: "imported",
    suggestedItemType: "external_article",
    title: "The way Atlanta startups share links is changing",
    excerpt: "A local startup story about curated collections, link sharing, and how founders are organizing useful resources.",
    url: "https://hypepotamus.com/atlanta/stacklist-link-sharing?utm_source=rss",
    canonicalUrl: "https://hypepotamus.com/atlanta/stacklist-link-sharing",
    guid: "hypepotamus-stacklist-link-sharing",
    publishedAt: "2026-07-17T14:30:00.000Z",
    fetchedAt: "2026-07-17T15:00:00.000Z",
    language: "en",
    categories: ["Atlanta", "Startups", "Technology"]
  },
  {
    id: "candidate-hypepotamus-black-tech-ai-commerce",
    sourceId: "hypepotamus",
    sourceName: "Hypepotamus",
    feedId: "black-tech",
    state: "imported",
    suggestedItemType: "external_article",
    title: "An Atlanta founder wants to bring checkout into AI chat",
    excerpt: "A practical local tech story for builders tracking commerce, AI interfaces, and startup execution.",
    url: "https://hypepotamus.com/companies/agentix-ai-commerce?utm_source=rss",
    canonicalUrl: "https://hypepotamus.com/companies/agentix-ai-commerce",
    guid: "hypepotamus-agentix-ai-commerce",
    publishedAt: "2026-07-17T11:20:00.000Z",
    fetchedAt: "2026-07-17T12:00:00.000Z",
    language: "en",
    categories: ["Atlanta", "Startups", "AI"]
  },
  {
    id: "candidate-conversation-creative-attention",
    sourceId: "the-conversation",
    sourceName: "The Conversation",
    feedId: "creative-community",
    state: "imported",
    suggestedItemType: "external_article",
    title: "What research says about attention, reading, and creative work",
    excerpt: "An expert-written piece connecting UX design, attention habits, media culture, and the way people make sense of information.",
    url: "https://theconversation.com/what-research-says-about-attention-reading-and-creative-work",
    canonicalUrl: "https://theconversation.com/what-research-says-about-attention-reading-and-creative-work",
    guid: "conversation-attention-reading-creative-work",
    publishedAt: "2026-07-17T16:00:00.000Z",
    fetchedAt: "2026-07-17T16:30:00.000Z",
    language: "en",
    categories: ["UX Design", "Culture", "Science", "Education"]
  },
  {
    id: "candidate-conversation-black-tech-work",
    sourceId: "the-conversation",
    sourceName: "The Conversation",
    feedId: "black-tech",
    state: "imported",
    suggestedItemType: "external_article",
    title: "How technology is changing work without changing what workers need",
    excerpt: "A practical research-backed look at technology, builders, labor, equity, and what people need from modern workplaces.",
    url: "https://theconversation.com/how-technology-is-changing-work-without-changing-what-workers-need",
    canonicalUrl: "https://theconversation.com/how-technology-is-changing-work-without-changing-what-workers-need",
    guid: "conversation-technology-work-workers",
    publishedAt: "2026-07-17T10:45:00.000Z",
    fetchedAt: "2026-07-17T11:15:00.000Z",
    language: "en",
    categories: ["Technology", "Work", "Society"]
  },
  {
    id: "candidate-mental-floss-history-language",
    sourceId: "mental-floss",
    sourceName: "Mental Floss",
    feedId: "creative-community",
    state: "imported",
    suggestedItemType: "external_article",
    title: "A curious history of everyday words people still use",
    excerpt: "A light but useful language-history piece for readers who like surprising context and memorable details.",
    url: "https://www.mentalfloss.com/posts/history-everyday-words",
    canonicalUrl: "https://www.mentalfloss.com/posts/history-everyday-words",
    guid: "mental-floss-everyday-words",
    publishedAt: "2026-07-17T08:30:00.000Z",
    fetchedAt: "2026-07-17T09:00:00.000Z",
    language: "en",
    categories: ["Language", "History", "Culture"]
  }
];
